### ISSUE TITLE
we have to add a max width for our main container we will solve it , so that user can feel good experience, thank you

### ISSUE THREAD

**Issue by SIFAT-AOC** [akash-khan-311/softui#215]
![git problem](https://github.com/akash-khan-311/softui/assets/97013103/b50c8906-7f5c-48e8-93df-270ab38a1cd0)

**Comment by akash-khan-311** [comment]
Thank so much notice that...

**Comment by akash-khan-311** [comment]
> ![git problem](https://private-user-images.githubusercontent.com/97013103/308652274-b50c8906-7f5c-48e8-93df-270ab38a1cd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxOTYwMDgsIm5iZiI6MTcwOTE5NTcwOCwicGF0aCI6Ii85NzAxMzEwMy8zMDg2NTIyNzQtYjUwYzg5MDYtN2Y1Yy00OGU4LTkzZGYtMjcwYWIzOGExY2QwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDA4MzUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ODM4NDA1NGFhNmNmMmY0YjJkNzQ3YWI5YzMyNTk2MWFhNDUzNjAwNGY3OWYzOGIxNmFmMDU1NjJmMzRmNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DAwzI4tVu6YJN_mH9ANfQcoCM5ykDW8dcdX68UwcSk0)
